services:
  fastapi:
    depends_on:
      - postgres
    container_name: fastapi
    build:
      context: .
      dockerfile: config/docker/Dockerfile_FastApi
    volumes:
      - ./app:/usr/src/app
      - .env:/usr/src/.env
    ports:
      - 8000:8000

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=todolist
volumes:
  postgres_data:
